http_addr = ":8080"
grpc_addr = ":8081"
grpc_cl_addr = "localhost:8081"
log_level = "debug"
database_url = "host=localhost dbname=customer_serv sslmode=disable user=postgres password=QSD73qa"
broker_addr = "localhost:9092"